name: finTechEnv
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.8
  - pip
  - pymongo
  - numpy
  - pandas
  - requests
  - grequests
  - requests-futures
  - requests-threads
  - aiohttp
  - aiodns
  - cchardet
  - websocket-client
  - gevent
  - gevent[recommended]
  - numba
  - bottleneck
  - numexpr
  - dask
  - intel-openmp
  - pytz
  - iso8601
  - ciso8601
  - statsmodels
  - matplotlib
  - mplfinance